nginx_log_file: ~/cloudfoundry/.deployments/devbox/log/nginx/nginx_router_access.log
app_log_dir: /var/vcap.local/router/nginx

jca_url: http://10.28.169.133/log/update.action
local_host: 127.0.0.1

#db_host: localhost
#db_port: 27017
#db_user:
#db_pwd: