host: 127.0.0.1
nginxlog: /home/lixc/cloudfoundry/.deployments/devbox/log/nginx/nginx_router_access.log
applogpath: /var/vcap.local/router/nginx
logip: 10.28.169.133
db_host: localhost
db_port: 27017
#db_user:
#db_pwd: